name: E2E Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  workflow_dispatch:

jobs:
  chrome:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4.1.2

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: setup python
      uses: actions/setup-python@v5.0.0
      with: 
        python-version: 3.12

    - name: Install Deps 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Browser init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:chromium tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Report
      uses: actions/upload-artifact@v4.3.3  
      if: always()
      with:
        name: Chrome Test report
        path: logs

  firefox:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4.1.2

    - name: Use Node.js 20
      uses: actions/setup-node@v4.0.2
      with:
        node-version: 20

    - name: setup python
      uses: actions/setup-python@v5.0.0
      with: 
        python-version: 3.12

    - name: Install Deps 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Browser init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:firefox tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      if: always()
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        report_path: logs

    - name: Upload Report
      uses: actions/upload-artifact@v4.3.3  
      if: always()
      with:
        name: Firefox Test report 
        path: logs

